from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]

# Generated by Django 5.2.6 on 2025-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
